create type figuretype as enum ('ARCHETYPE', 'SYMBOL');

CREATE TABLE figures(
    id uuid primary key default gen_random_uuid(),
    name varchar(32) not null,
    brief varchar(128) not null,
    description varchar(512) not null,
    figure figuretype not null
);

INSERT INTO figures (name, brief, description, figure) VALUES
    ('Kahraman', 'Cesur kurtarıcı figür.', 'Zorluklar karşısında cesaret ve fedakarlık gösteren, engelleri aşarak dönüşüm yaşayan figür.', 'ARCHETYPE'),
    ('Gölge', 'Bastırılmış karanlık yön.', 'Bilinçaltında saklanan, reddedilen veya görmezden gelinen kişisel yönleri temsil eder.', 'ARCHETYPE'),
    ('Bilge Yaşlı Adam', 'Tecrübeli rehber figür.', 'Bilgelik, bilgi ve yol göstericilik sunan yaşlı erkek figürü.', 'ARCHETYPE'),
    ('Bilge Yaşlı Kadın', 'Sezgisel rehber figür.', 'Ruhsal bilgi ve derin anlayış sunan yaşlı kadın figürü.', 'ARCHETYPE'),
    ('Düzenbaz', 'Kurnaz dönüştürücü.', 'Kuralları bozan, mizah ve kaos yoluyla değişim yaratan figür.', 'ARCHETYPE'),
    ('Anima', 'Erkekteki dişil yön.', 'Duygular, sezgiler ve yaratıcılıkla bağlantılı bilinçdışı dişil enerji.', 'ARCHETYPE'),
    ('Animus', 'Kadındaki eril yön.', 'Mantık, aksiyon ve iradeyle bağlantılı bilinçdışı eril enerji.', 'ARCHETYPE'),
    ('İlahi Çocuk', 'Saf başlangıç enerjisi.', 'Masumiyet, umut ve potansiyelin simgesi.', 'ARCHETYPE'),
    ('Yetim Çocuk', 'Kaybolmuşluk ve yalnızlık.', 'Destek arayışı içinde olan, aidiyet ihtiyacı duyan figür.', 'ARCHETYPE'),
    ('Savaşçı', 'Güçlü koruyucu.', 'Değerlerini korumak için mücadele eden, irade ve cesaret sahibi figür.', 'ARCHETYPE'),
    ('Aşık', 'Tutkulu bağ kuran.', 'Sevgi, bağlılık ve estetik duygularla hareket eden figür.', 'ARCHETYPE'),
    ('Yaratıcı', 'Üretken yenilikçi.', 'Hayal gücüyle yeni fikirler ve eserler ortaya koyan figür.', 'ARCHETYPE'),
    ('Hükümdar', 'Otorite ve düzen sağlayıcı.', 'Güç, düzen ve sorumluluk bilinciyle liderlik eden figür.', 'ARCHETYPE'),
    ('Büyücü', 'Dönüştürücü güç sahibi.', 'Enerji ve bilgi aracılığıyla değişim yaratan figür.', 'ARCHETYPE'),
    ('Arayan', 'Gerçeği arayan yolcu.', 'Anlam, özgürlük veya hakikat arayışındaki figür.', 'ARCHETYPE'),
    ('Sadık Dost', 'Güvenilir destekçi.', 'Bağlılık ve fedakârlıkla dostluk sürdüren figür.', 'ARCHETYPE'),
    ('Kurban', 'Feda eden figür.', 'Başarı veya düzen uğruna kendini adayan kişi.', 'ARCHETYPE'),
    ('İsyancı', 'Kurallara karşı çıkan.', 'Baskıcı sisteme karşı özgürlük arayan figür.', 'ARCHETYPE'),
    ('Anne', 'Besleyici ve koruyucu.', 'Şefkat, doğurganlık ve büyütme enerjisini temsil eden figür.', 'ARCHETYPE'),
    ('Baba', 'Yol gösterici ve koruyucu.', 'Otorite, destek ve rehberlik sağlayan figür.', 'ARCHETYPE');

INSERT INTO figures (name, brief, description, figure) VALUES
    ('Su', 'Duyguların sembolü.', 'Bilinçaltı, duygusal durum ve yaşamın akışını temsil eder. Sakin su huzuru, fırtınalı su içsel çalkantıyı gösterir.', 'SYMBOL'),
    ('Ev', 'Kendilik yapısı.', 'Kişinin iç dünyasını ve yaşam alanını temsil eder. Odalar farklı kişilik yönlerini simgeler.', 'SYMBOL'),
    ('Yılan', 'Dönüşüm ve gizli tehlike.', 'Yenilenme, bilinçdışı güçler veya bastırılmış korkularla ilişkilendirilir. Bazı kültürlerde şifa sembolüdür.', 'SYMBOL'),
    ('Uçmak', 'Özgürlük ve kaçış.', 'Kontrolden kurtulma, özgürleşme veya sorunlardan uzaklaşma isteğini ifade eder.', 'SYMBOL'),
    ('Ölüm', 'Bitiş ve dönüşüm.', 'Bir durumun sona erdiğini ve yeni bir başlangıcın yaklaştığını simgeler.', 'SYMBOL'),
    ('Orman', 'Bilinmezlik ve arayış.', 'Bilinçaltı keşfi, kaybolma ve kendini bulma süreçlerini temsil eder.', 'SYMBOL'),
    ('Ateş', 'Tutku ve yıkım.', 'Güçlü enerji, arzu veya öfkeyi simgeler. Arınma ve dönüşümle de ilişkilidir.', 'SYMBOL'),
    ('Yol', 'Yaşam yolu.', 'Hayattaki ilerleyiş, kararlar ve yön değiştirme noktalarını temsil eder.', 'SYMBOL'),
    ('Köprü', 'Geçiş ve bağlantı.', 'Hayatın bir aşamasından diğerine geçişi veya iki durum arasında bağlantıyı simgeler.', 'SYMBOL'),
    ('Kapı', 'Fırsat ve değişim.', 'Yeni başlangıçlara açılan veya engel oluşturan geçitleri temsil eder.', 'SYMBOL'),
    ('Dağ', 'Zorluk ve hedef.', 'Aşılması gereken engelleri veya ulaşılacak hedefleri simgeler.', 'SYMBOL'),
    ('Güneş', 'Yaşam enerjisi.', 'Pozitiflik, güç ve aydınlanmayı simgeler.', 'SYMBOL'),
    ('Ay', 'Sezgi ve döngü.', 'Duygular, bilinçdışı ve yaşam döngülerini temsil eder.', 'SYMBOL'),
    ('Kedi', 'Bağımsızlık ve sezgi.', 'Özgürlük, gizem ve içgüdüleri temsil eder.', 'SYMBOL'),
    ('Köpek', 'Sadakat ve koruma.', 'Güven, dostluk ve bağlılığı simgeler.', 'SYMBOL'),
    ('Bebek', 'Yeni başlangıç.', 'Masumiyet, potansiyel ve gelişimi temsil eder.', 'SYMBOL'),
    ('Ayna', 'Kendini görme.', 'Kendi kimliğini, içsel gerçeği veya yansımayı simgeler.', 'SYMBOL'),
    ('Kan', 'Yaşam gücü.', 'Hayati enerji, tutku veya kayıp anlamına gelir.', 'SYMBOL'),
    ('Araba', 'Kendi kontrolün.', 'Hayattaki yönünü ve ilerleyişini simgeler.', 'SYMBOL'),
    ('Telefon', 'Bağlantı ve iletişim.', 'İlişkilerdeki iletişim durumu veya mesaj alma isteğini temsil eder.', 'SYMBOL'),
    ('Kilit', 'Gizlilik ve güvenlik.', 'Saklanan sırlar veya korunma ihtiyacı.', 'SYMBOL'),
    ('Anahtar', 'Çözüm ve erişim.', 'Engellerin aşılması veya fırsatların kilidinin açılması.', 'SYMBOL'),
    ('Deniz', 'Bilinçaltı derinlikleri.', 'Geniş ufuklar, duygular ve bilinçdışını temsil eder.', 'SYMBOL'),
    ('Balık', 'Bereket ve maneviyat.', 'Zenginlik, sezgi ve bilinçdışı akış.', 'SYMBOL'),
    ('Kuş', 'Özgürlük ve umut.', 'Yükseğe ulaşma ve hafifleme isteğini simgeler.', 'SYMBOL'),
    ('Köprüden Geçmek', 'Değişim süreci.', 'Bir aşamadan diğerine geçişin aktif deneyimi.', 'SYMBOL'),
    ('Merdiven', 'Yükseliş ve iniş.', 'Gelişim, hedefe ulaşma veya bilinçaltına iniş.', 'SYMBOL'),
    ('Çiçek', 'Güzellik ve gelişim.', 'Doğal büyüme ve açılım sürecini simgeler.', 'SYMBOL'),
    ('Elbise', 'Kimlik ve imaj.', 'Kendini dış dünyaya nasıl sunduğunu temsil eder.', 'SYMBOL'),
    ('Yağmur', 'Arınma ve yenilenme.', 'Eski duyguların temizlenmesini veya yeni duygusal başlangıçları simgeler.', 'SYMBOL'),
    ('Gemi', 'Yolculuk ve keşif.', 'Hayatın akışı boyunca bilinmeyene doğru ilerleyiş.', 'SYMBOL'),
    ('Bulut', 'Belirsizlik ve gizlenme.', 'Net olmayan durumlar, duygusal karmaşa veya gizlenmiş gerçekler.', 'SYMBOL'),
    ('Kule', 'Güç ve yalnızlık.', 'Otorite, güç veya izole edilmişlik hissi.', 'SYMBOL'),
    ('Pencere', 'Bakış açısı.', 'Fırsatları veya dış dünyaya açılan bağlantıyı temsil eder.', 'SYMBOL'),
    ('Tünel', 'Geçiş ve dar yol.', 'Zor bir süreçten geçiş veya bilinçaltına iniş.', 'SYMBOL'),
    ('Harita', 'Yön bulma.', 'Hayatta yolunu arama, plan yapma ve hedef belirleme.', 'SYMBOL'),
    ('Çöl', 'Yalnızlık ve zorluk.', 'Kaynak eksikliği, umutsuzluk veya dayanıklılık sınavı.', 'SYMBOL'),
    ('Buz', 'Duygusal donukluk.', 'Hareketin ve duyguların geçici olarak durması.', 'SYMBOL'),
    ('Göz', 'Farkındalık ve sezgi.', 'Görmek, bilmek veya gözetlenmek anlamına gelebilir.', 'SYMBOL'),
    ('Maske', 'Gizleme ve rol.', 'Gerçek kimliği saklamak veya sahte bir imaj sunmak.', 'SYMBOL'),
    ('Para', 'Değer ve güç.', 'Maddi kazanç, özgüven veya fırsat.', 'SYMBOL'),
    ('Yıldız', 'Umut ve ilham.', 'Yön gösterici ışık veya yüksek idealler.', 'SYMBOL'),
    ('Ağaç', 'Yaşam ve kökler.', 'Büyüme, aile ve istikrar.', 'SYMBOL'),
    ('Kuyu', 'Derinlik ve bilinçaltı.', 'Gizli duygular veya bilgi kaynakları.', 'SYMBOL'),
    ('İp', 'Bağlantı ve sınır.', 'Kısıtlama veya destek.', 'SYMBOL'),
    ('Köprü Altı', 'Engellerin gölgesi.', 'Olumsuz geçiş deneyimleri veya gizli tehlikeler.', 'SYMBOL'),
    ('Asansör', 'Hızlı değişim.', 'Yükseliş veya düşüş süreçlerini simgeler.', 'SYMBOL'),
    ('Balon', 'Hafiflik ve kaçış.', 'Sorunlardan uzaklaşma veya çocukça sevinç.', 'SYMBOL'),
    ('Kitap', 'Bilgi ve öğrenme.', 'Gerçeklerin keşfi veya kişisel gelişim.', 'SYMBOL'),
    ('Mum', 'Işık ve rehberlik.', 'Karanlıkta yön bulma veya umut.', 'SYMBOL'),
    ('Saat', 'Zaman ve sınırlılık.', 'Fırsatların geçiciliği veya sabırsızlık.', 'SYMBOL'),
    ('Yüzük', 'Bağlılık ve birlik.', 'İlişkilerde süreklilik veya söz.', 'SYMBOL'),
    ('Tüy', 'Hafiflik ve özgürlük.', 'Ruhsal yükseliş veya korunma.', 'SYMBOL'),
    ('Kafes', 'Kısıtlama ve hapis.', 'Özgürlüğün engellenmesi.', 'SYMBOL'),
    ('Köprü Tahtası', 'Dengesizlik.', 'Geçiş sırasında dikkat gerekliliği.', 'SYMBOL'),
    ('Toprak', 'Temel ve güvenlik.', 'Köklenme, dayanıklılık veya maddi yaşam.', 'SYMBOL'),
    ('Volkan', 'Patlama ve baskı.', 'Bastırılmış duyguların aniden ortaya çıkması.', 'SYMBOL'),
    ('Gözyaşı', 'Duygusal boşalma.', 'Üzüntü veya rahatlama.', 'SYMBOL'),
    ('Mezar', 'Bitiş ve anı.', 'Geçmişin kapanışı veya hatırlama.', 'SYMBOL'),
    ('Heykel', 'Durağanlık ve hatıra.', 'Zamanda donmuş anılar veya idealler.', 'SYMBOL'),
    ('Zincir', 'Bağlılık veya esaret.', 'Özgürlük kısıtlaması.', 'SYMBOL'),
    ('Köprü Direği', 'Destek noktası.', 'Geçişin güvenliği.', 'SYMBOL'),
    ('İskambil Kartı', 'Şans ve risk.', 'Hayatın kumarını temsil eder.', 'SYMBOL'),
    ('Şemsiye', 'Koruma.', 'Duygusal veya fiziksel korunma.', 'SYMBOL'),
    ('Bisiklet', 'Denge ve hareket.', 'Kendi gücünle ilerleme.', 'SYMBOL'),
    ('Çan', 'Uyarı ve dikkat.', 'Tehlike veya önemli bir gelişme.', 'SYMBOL'),
    ('Sandalye', 'Dinlenme ve bekleme.', 'Hareketsizlik veya otorite.', 'SYMBOL'),
    ('Kamera', 'Kaydetme.', 'Geçmiş anıların saklanması.', 'SYMBOL'),
    ('Deniz Feneri', 'Yol gösterici.', 'Tehlikede yön bulma.', 'SYMBOL'),
    ('Gölge', 'Bilinmeyen yan.', 'Karanlık tarafla yüzleşme.', 'SYMBOL'),
    ('Pusula', 'Yön tayini.', 'Hayattaki yönünü bulma.', 'SYMBOL'),
    ('Hap', 'Şifa veya bağımlılık.', 'Sorun çözümü veya yeni sorunlar.', 'SYMBOL'),
    ('Bıçak', 'Tehlike ve keskinlik.', 'Ayırma veya koruma.', 'SYMBOL'),
    ('Masa', 'Bir araya gelme.', 'Toplanma veya paylaşım.', 'SYMBOL'),
    ('Lamba', 'Aydınlanma.', 'Fikir veya farkındalık.', 'SYMBOL'),
    ('Halat', 'Bağlantı.', 'Güvenlik veya kısıtlama.', 'SYMBOL'),
    ('Kale', 'Koruma.', 'Güç ve güvenlik.', 'SYMBOL'),
    ('Köprü Yolu', 'Bağlantı.', 'İki nokta arasındaki geçiş.', 'SYMBOL'),
    ('Labirent', 'Karmaşıklık.', 'Çıkış yolu arama.', 'SYMBOL'),
    ('Teleskop', 'Görüş genişliği.', 'Uzak hedeflere odaklanma.', 'SYMBOL'),
    ('Radyo', 'Mesaj.', 'Duygusal veya zihinsel ileti.', 'SYMBOL'),
    ('Kule Çanı', 'Uyarı.', 'Tehlike veya haber.', 'SYMBOL'),
    ('Taç', 'Zafer.', 'Başarı ve otorite.', 'SYMBOL'),
    ('Yol Ayrımı', 'Karar.', 'Seçim yapma anı.', 'SYMBOL'),
    ('Çapa', 'Sabitlik.', 'Güvenlik ve istikrar.', 'SYMBOL'),
    ('Kertenkele', 'Uyum.', 'Çevreye adaptasyon.', 'SYMBOL'),
    ('Kartal', 'Güç ve özgürlük.', 'Yüksekten bakma yetisi.', 'SYMBOL'),
    ('Kurt', 'Sadakat ve vahşilik.', 'Topluluk veya yalnızlık.', 'SYMBOL'),
    ('At', 'Güç ve hareket.', 'Özgürlük ve ilerleme.', 'SYMBOL'),
    ('Koyun', 'Masumiyet.', 'Uysallık ve teslimiyet.', 'SYMBOL'),
    ('Aslan', 'Güç ve liderlik.', 'Cesaret ve hakimiyet.', 'SYMBOL'),
    ('Fil', 'Bilgelik ve hafıza.', 'Sadakat ve güç.', 'SYMBOL'),
    ('Yusufçuk', 'Değişim.', 'Hafiflik ve dönüşüm.', 'SYMBOL'),
    ('Kelebek', 'Dönüşüm ve güzellik.', 'Değişim süreci.', 'SYMBOL'),
    ('Arı', 'Çalışkanlık ve birlik.', 'Üretkenlik ve işbirliği.', 'SYMBOL'),
    ('Karınca', 'Düzen ve emek.', 'Kolektif çalışma.', 'SYMBOL'),
    ('Örümcek', 'Ağ ve kader.', 'Plan ve strateji.', 'SYMBOL'),
    ('Yengeç', 'Koruma ve duyarlılık.', 'Savunma mekanizmaları.', 'SYMBOL'),
    ('Ahtapot', 'Çok yönlülük.', 'Esneklik ve kontrol.', 'SYMBOL'),
    ('Deniz Yıldızı', 'Şifa.', 'Yenilenme ve direnç.', 'SYMBOL');